### ISSUE TITLE
Reserve the crate name

### ISSUE THREAD

**Issue by r3v2d0g** [oliver-giersch/debra#1]
I think that you should register the crate since you are advertising it on the repo's README and just in case someone wants to implement the DEBRA(+) paper too ;).

If you don't feel ready to release a first version, I'd suggest that you publish an empty crate with its version set to `0.0.0`.

**Comment by oliver-giersch** [comment]
Thanks for the suggestion,
the crate and some of its dependencies also written by me are not yet ready, but I've released a 0.0.0 version on crates.io
